"""
keygen.py — Generate ECDSA keypairs for all hospital users.

Writes:
  - users_config.json  : public keys + roles (safe to commit)
  - .env               : private keys (NEVER commit this file)

Run once to bootstrap the system, then keep .env secret.
Usage:
    python keygen.py
"""

import json
import os
import secrets
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

USERS_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "users_config.json")
ENV_PATH = os.path.join(os.path.dirname(__file__), ".env")

users = {
    "DOC-505": {"role": "Doctor"},
    "DOC-911": {"role": "Doctor"},
    "REC-101": {"role": "Receptionist"},
    "NUR-202": {"role": "Nurse"},
}

public_config = {}
private_env_lines = [
    "# Auto-generated by keygen.py — DO NOT COMMIT THIS FILE",
    f"RESET_TOKEN={secrets.token_hex(32)}",
    f"API_KEY={secrets.token_hex(32)}",
    "FLASK_HOST=127.0.0.1",
    "FLASK_PORT=5000",
    "DEMO_MODE=false",
    "",
]

for uid, info in users.items():
    private_key = ec.generate_private_key(ec.SECP256R1())

    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()

    # Public config: roles + public keys only (safe to store/commit)
    public_config[uid] = {
        "role": info["role"],
        "public_key": public_pem,
    }

    # Private keys go to .env (one line per user, newlines escaped)
    env_key = f"PRIVATE_KEY_{uid.replace('-', '_')}"
    private_pem_oneline = private_pem.replace("\n", "\\n")
    private_env_lines.append(f'{env_key}={private_pem_oneline}')

# Write public config
with open(USERS_CONFIG_PATH, "w", encoding="utf-8") as f:
    json.dump(public_config, f, indent=2)
print(f"[+] Public keys written to {USERS_CONFIG_PATH}")

# Write .env (create or overwrite)
with open(ENV_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(private_env_lines) + "\n")
print(f"[+] Private keys written to {ENV_PATH}")
print("[!] Keep .env secret — never commit it to version control.")
